# Generated by Django 2.1.4 on 2018-12-16 22:47

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime(2018, 12, 16, 22, 47, 23, 39370))),
                ('updated', models.DateField(default=datetime.datetime(2018, 12, 16, 22, 47, 23, 39439))),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('success', models.TextField(null=True)),
                ('crit_success', models.TextField(null=True)),
                ('fail', models.TextField(null=True)),
                ('crit_failure', models.TextField(null=True)),
                ('level', models.SmallIntegerField()),
                ('trigger', models.TextField(null=True)),
                ('actions', models.SmallIntegerField()),
                ('traits', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
