# Generated by Django 2.1.4 on 2018-12-16 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='special',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 22, 52, 53, 341867)),
        ),
        migrations.AlterField(
            model_name='feat',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 22, 52, 53, 342036)),
        ),
    ]
