# Generated by Django 2.1.4 on 2018-12-16 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feats', '0002_auto_20181216_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='actions',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 22, 53, 22, 793686)),
        ),
        migrations.AlterField(
            model_name='feat',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 22, 53, 22, 793779)),
        ),
    ]
