# Generated by Django 2.1.4 on 2018-12-17 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feats', '0003_auto_20181216_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 17, 20, 4, 7, 825430)),
        ),
        migrations.AlterField(
            model_name='feat',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 17, 20, 4, 7, 825493)),
        ),
    ]
