# Generated by Django 2.1.4 on 2018-12-11 21:22

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('success', models.TextField()),
                ('crit_success', models.TextField()),
                ('fail', models.TextField()),
                ('crit_fail', models.TextField()),
                ('type', models.CharField(max_length=80)),
                ('verbal', models.BooleanField()),
                ('somatic', models.BooleanField()),
                ('material', models.TextField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
