# Generated by Django 2.1.4 on 2018-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_auto_20181212_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
