# Generated by Django 2.1.4 on 2018-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_auto_20181212_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
