# Generated by Django 2.1.4 on 2018-12-12 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_auto_20181212_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 12, 30, 11282)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='crit_failure',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='crit_success',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='fail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='success',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 12, 30, 11331)),
        ),
    ]
