# Generated by Django 2.1.4 on 2018-12-12 04:13

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0006_auto_20181212_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 13, 27, 54192)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='heightened',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='somatic',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='traits',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 13, 27, 54245)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='verbal',
            field=models.BooleanField(null=True),
        ),
    ]
