# Generated by Django 2.1.4 on 2018-12-12 04:14

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_auto_20181212_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='table',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 14, 0, 563313)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 14, 0, 563363)),
        ),
    ]
