# Generated by Django 2.1.4 on 2018-12-12 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0008_auto_20181212_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 15, 52, 312748)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 15, 52, 312797)),
        ),
    ]
