# Generated by Django 2.1.4 on 2018-12-12 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0009_auto_20181212_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='trigger',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 17, 46, 768414)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 17, 46, 768465)),
        ),
    ]
