# Generated by Django 2.1.4 on 2018-12-12 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0011_auto_20181212_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='area',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 20, 24, 315156)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 20, 24, 315224)),
        ),
    ]
