# Generated by Django 2.1.4 on 2018-12-12 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0014_auto_20181212_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 22, 10, 623528)),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='updated',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 4, 22, 10, 623624)),
        ),
    ]
