# Generated by Django 2.1.5 on 2019-02-06 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 2, 6, 3, 32, 7, 835436)),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated',
            field=models.DateField(default=datetime.datetime(2019, 2, 6, 3, 32, 7, 835498)),
        ),
    ]
