# Generated by Django 2.1.5 on 2019-02-07 16:48

import datetime
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=django_bleach.models.BleachField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 16, 48, 11, 974198)),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 16, 48, 11, 974284)),
        ),
    ]
