# Generated by Django 2.1.5 on 2019-02-07 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190207_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='y_posiiton',
            new_name='y_position',
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 17, 13, 55, 264758)),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 17, 13, 55, 264834)),
        ),
    ]
